### **Anmol Yadav**
### **Task 6 : Prediction Using Decision Tree Algorithm**


In [1]:
#Import dependencies 


import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.tree import DecisionTreeClassifier
from sklearn import model_selection
from sklearn import datasets

In [2]:
#Load the data 
iris=datasets.load_iris()
x=pd.DataFrame(iris.data, columns=iris.feature_names)

In [3]:
y=pd.DataFrame(iris.target,columns=["Species"])

### **Split the the into 80% training and 20% testing datasets**

In [4]:
X_train,X_test,y_train,y_test=model_selection.train_test_split(x,y,test_size=0.2, random_state=0)

### **Create Decision tree classifier and train on training data**

In [5]:
dtc= DecisionTreeClassifier().fit(X_train,y_train)

### **Prediction on training data**

In [6]:
pred = dtc.predict(X_train)
pred

array([2, 1, 0, 2, 2, 1, 0, 1, 1, 1, 2, 0, 2, 0, 0, 1, 2, 2, 2, 2, 1, 2,
       1, 1, 2, 2, 2, 2, 1, 2, 1, 0, 2, 1, 1, 1, 1, 2, 0, 0, 2, 1, 0, 0,
       1, 0, 2, 1, 0, 1, 2, 1, 0, 2, 2, 2, 2, 0, 0, 2, 2, 0, 2, 0, 2, 2,
       0, 0, 2, 0, 0, 0, 1, 2, 2, 0, 0, 0, 1, 1, 0, 0, 1, 0, 2, 1, 2, 1,
       0, 2, 0, 2, 0, 0, 2, 0, 2, 1, 1, 1, 2, 2, 1, 1, 0, 1, 2, 2, 0, 1,
       1, 1, 1, 0, 0, 0, 2, 1, 2, 0])

In [7]:
y_train

Species
137        2
84         1
27         0
127        2
132        2
..       ...
9          0
103        2
67         1
117        2
47         0

[120 rows x 1 columns]

### **Predicion in testing data**

In [8]:
test_pred = dtc.predict(X_test)
test_pred

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0])

In [9]:
y_test

Species
114        2
62         1
33         0
107        2
7          0
100        2
40         0
86         1
76         1
71         1
134        2
51         1
73         1
54         1
63         1
37         0
78         1
90         1
45         0
16         0
121        2
66         1
24         0
8          0
126        2
22         0
44         0
97         1
93         1
26         0

### **Checking precision, recall and f1-score**

In [10]:
from sklearn.metrics import classification_report
print(classification_report(test_pred,y_test))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00         6

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



### **Evaluating the decision trees using entropy**

In [11]:
classifier= DecisionTreeClassifier(criterion='entropy',random_state=0).fit(X_train,y_train)

In [12]:
classifier.score(X_test,y_test)

1.0

In [13]:
y_pred = classifier.predict(X_test)
y_pred

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0])

In [14]:
y_test

Species
114        2
62         1
33         0
107        2
7          0
100        2
40         0
86         1
76         1
71         1
134        2
51         1
73         1
54         1
63         1
37         0
78         1
90         1
45         0
16         0
121        2
66         1
24         0
8          0
126        2
22         0
44         0
97         1
93         1
26         0

### **Visualising decision tree**

In [15]:
from sklearn import tree
fig = plt.figure(figsize=(25,20))
_ = tree.plot_tree(dtc, 
                   feature_names=iris.feature_names,  
                   class_names=iris.target_names,
                   filled=True)